### ISSUE TITLE
Hi!

### ISSUE THREAD

**Issue by MicMiao** [acdzh/ama#1]
Hi Vukk,
Thanks a lot for your douban-api! I'm currently trying to build a Recommender system for children books to be used by non-profits organizations in China. I am trying to build a database with data coming from douban. I have already intalled your repository and launch the app. All I see is a "hello page". I apologize for my unexperience, I'm super newbie in this. I would really appreciate if you can help me to setup the API correctly. In particular, I guess I will need to implement the following steps:

- setup a empty database either MySQL or Postgre, I have both and will be able to use either of them;
- link the API to the database
- understand how to use the API, in particular how to define my queries. For example, I would like to download data from all books with the tag:童书 at this page  https://book.douban.com/tag/%E7%AB%A5%E4%B9%A6, these are more than 2000 books. How would I do it?

Thank you so much again for your time and help. 

All the best,

Michele

**Comment by acdzh** [comment]
Hello,

> 看起来应该是国人,  那我就用中文回复了

这两天实在太忙, 不好意思现在才回复.

"hello page" 是因为, 首页确实是一个 hello page. 你需要访问 [README](https://github.com/acdzh/douban-book-api/blob/master/README.md) 中给出的地址才行. 举个例子来说 (假设首页的地址是 `http://localhost:3000/` ), 图书搜索接口的请求地址是在 README 中是 `{HOST}/search/<text>`, 意思是, 如果你想搜索 `童书` 关键词的话, 你需要访问 `http://localhost:3000/search/童书` 这个地址. 其他几个接口亦然.

关于数据库的问题, 这个需要有一定的编程知识去使用. 这里就不说了, 建议先简单自学一下.

这个 API 可以以 HTTP 服务的方式使用, 如果你熟悉 node 的话, 也可以直接使用 ./douban 目录下的 js lib.

最后还有一个问题, 这个东西目前只能搜索第一页的结果. 因此如果需要返回多页结果, 还需要做一些改造. 这一点 [README 里也有提到](https://github.com/acdzh/douban-book-api#%E5%A4%87%E6%B3%A8). 从另一个角度来说, 现在应该还满足不了你的需求.
如果可以的话, 可以在此基础上增加一个 searchByTag 的功能, 会更好一些.

**Comment by MicMiao** [comment]
多谢，多谢！ 
基本上有了个头绪。 我自己再研究一下。 

Thanks again!

Michele
